//variable join
let first_name="Maung" ;
let last_name="Kyaw";
let name=first_name+last_name;
console.log(name)

//Time Function
console.time("Time Record")
console.log("Happy");
console.log("Happy");
console.log("Happy");
console.log("Happy");
console.log("Happy");
console.log("Happy");
console.timeEnd("Time Record")
/*
let first_name //underscoren convention
let FirstName //pascale case
let firstName //camle case
let First_Name //snake case ,const variable
*/

